extend = "ruff_defaults.toml"

# https://github.com/astral-sh/ruff/issues/8627
exclude = [".git", ".mypy_cache", ".ruff_cache", ".venv", "dist"]

[format]
preview = true
quote-style = "single"

[lint]
preview = true
ignore = [
  # Allow lazy imports for responsive CLI
  "PLC0415",
]

[lint.isort]
known-first-party = ["hatch", "hatchling"]